# Generated by Django 6.0.4 on 2026-07-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailname', models.EmailField(max_length=254)),
            ],
        ),
    ]
