# Generated by Django 6.0.4 on 2026-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0004_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
